// Reviewed display names for all 65 St. George venues in the catalogue.
// Keep published names untouched for class details and full-name tooltips.
const venueNames = {
  AB: "Astronomy",
  AH: "Alumni Hall",
  AP: "Anthropology",
  BA: "Bahen Centre",
  BF: "Bancroft",
  BN: "Clara Benson",
  BR: "Brennan Hall",
  BT: "Bader Theatre",
  CH: "Convocation Hall",
  CR: "Carr Hall",
  DA: "Daniels",
  EJ: "Edward Johnson",
  EM: "Emmanuel College",
  EP: "Stewart",
  ES: "Earth Sciences",
  FE: "371 Bloor West",
  GB: "Galbraith",
  GI: "George Ignatieff",
  HA: "Haultain",
  HI: "St. Hilda's",
  HS: "Health Sciences",
  IN: "Innis College",
  JH: "Jackman Humanities",
  JP: "90 Wellesley West",
  KP: "Koffler House",
  LA: "Larkin",
  LI: "Lillian Massey",
  LM: "Lash Miller",
  MB: "Lassonde Mining",
  MC: "Mechanical Eng.",
  MK: "Munk Observatory",
  MP: "McLennan",
  MS: "Medical Sciences",
  MY: "Myhal",
  NB: "Borden North",
  NF: "Northrop Frye",
  NL: "Naylor",
  OH: "Odette Hall",
  OI: "OISE",
  PB: "Leslie Dan Pharmacy",
  PR: "E.J. Pratt Library",
  PT: "D.L. Pratt",
  RL: "Robarts",
  RO: "ROM",
  RS: "Rosebrugh",
  RT: "Rotman",
  RW: "Ramsay Wright",
  SB: "Borden South",
  SD: "Sir Daniel Wilson",
  SF: "Sandford Fleming",
  SK: "Social Work",
  SM: "Gerstein Library",
  SS: "Sidney Smith",
  SU: "40 Sussex",
  TC: "Trinity College",
  TF: "Teefy Hall",
  UC: "University College",
  UP: "UC Union",
  VC: "Victoria College",
  WB: "Wallberg",
  WE: "Wetmore Hall",
  WI: "Wilson Hall",
  WO: "Woodsworth Residence",
  WS: "Warren Stevens",
  WW: "Woodsworth College",
};

export function venueName(code, buildings) {
  return venueNames[code] || buildings[code]?.name || code;
}
